openai_key = "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"
amadeus_secret = "jG6BrCqYx06aIIsX"
amadeus_key = "Wm46dYunbVlKfv0mFMo3PvAeOIzpXIUi"
map_key = "vJCCnwiyG6_Ib2-hBIvfn5EDVTn0WlVQaKHWh48k41U"
