openai_key = "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"
amadeus_secret = "4itg7cBr2VIKSbxM"
amadeus_key = "fJ3uis9dPD2ZKlM576vk7ezwSxsj80Ai"
map_key = "vJCCnwiyG6_Ib2-hBIvfn5EDVTn0WlVQaKHWh48k41U"
