openai_key = "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"
amadeus_secret = "HAAyFjqZL9mlop7l"
amadeus_key = "LyzoBtAuGdgdv1LtFqCRIf49TAPeJY6F"
map_key = "vJCCnwiyG6_Ib2-hBIvfn5EDVTn0WlVQaKHWh48k41U"
