openai_key = "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"
amadeus_secret = "HAAyFjqZL9mlop7l"
amadeus_key = "LyzoBtAuGdgdv1LtFqCRIf49TAPeJY6F"
map_key = "vJCCnwiyG6_Ib2-hBIvfn5EDVTn0WlVQaKHWh48k41U"
